name: Build Reprate_Calculator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.11]

    steps:
      # ----------------------------
      # 1. Checkout repository
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------
      # 2. Set up Python
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------
      # 3. Install dependencies
      # ----------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      # ----------------------------
      # 4. Prepare assets folder (cross-platform)
      # ----------------------------
      - name: Prepare assets
        run: |
          python -c "
import shutil, os
os.makedirs('assets', exist_ok=True)
for f in ['Lumos_Logo_32x32.png','Lumos_Logo_32x32.ico','Lumos_Laser_Logo_1024x236.png','Osc_Diagram.png','Screenshot.png']:
    shutil.copy(f, 'assets')
"

      # ----------------------------
      # 5a. Build executable on Windows
      # ----------------------------
      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          pyinstaller main.py --onefile --windowed --icon=assets\Lumos_Logo_32x32.ico `
            --add-data "assets\Lumos_Logo_32x32.png;assets" `
            --add-data "assets\Lumos_Laser_Logo_1024x236.png;assets" `
            --add-data "assets\Osc_Diagram.png;assets" `
            --add-data "assets\Screenshot.png;assets"

      # ----------------------------
      # 5b. Build executable on macOS
      # ----------------------------
      - name: Build with PyInstaller (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          pyinstaller main.py \
            --onefile \
            --windowed \
            --icon=assets/Lumos_Logo_32x32.icns \
            --add-data "assets/Lumos_Logo_32x32.png:assets" \
            --add-data "assets/Lumos_Laser_Logo_1024x236.png:assets" \
            --add-data "assets/Osc_Diagram.png:assets" \
            --add-data "assets/Screenshot.png:assets"

      # ----------------------------
      # 6a. Zip macOS app (optional)
      # ----------------------------
      - name: Zip macOS app
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          cd dist
          zip -r Reprate_Calculator-macos.zip main

      # ----------------------------
      # 7. Upload artifact
      # ----------------------------
      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: Reprate_Calculator-${{ matrix.os }}
          pat
