name: Build Cross-Platform Executables

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller pillow

      - name: Build executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --windowed main.py
          else
            pyinstaller --onefile --windowed main.py
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Reprate_Calculator-${{ matrix.os }}
          path: |
            dist/main
            dist/main.exe
            dist/main.app

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Reprate_Calculator-Windows
          path: ./builds/windows
      - uses: actions/download-artifact@v3
        with:
          name: Reprate_Calculator-macos-latest
          path: ./builds/macos

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            ./builds/windows/*
            ./builds/macos/*
