name: Build Reprate_Calculator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.11]

    steps:
      # ----------------------------
      # 1. Checkout repository
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------
      # 2. Set up Python
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------
      # 3. Install dependencies
      # ----------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      # ----------------------------
      # 4. Prepare assets folder
      # ----------------------------
      - name: Prepare assets (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Force -Path assets
          Copy-Item Lumos_Logo_32x32.png,Lumos_Logo_32x32.ico,Lumos_Laser_Logo_1024x236.png,Osc_Diagram.png,Screenshot.png -Destination assets
        shell: pwsh

      - name: Prepare assets (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p assets
          cp Lumos_Logo_32x32.png Lumos_Logo_32x32.ico Lumos_Laser_Logo_1024x236.png Osc_Diagram.png Screenshot.png assets/
        shell: bash

      # ----------------------------
      # 5. Build executable/app
      # ----------------------------

      
      
      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller main.py --onefile --windowed --name Reprate_Calculator --icon=Lumos_Logo_32x32.ico --version-file=version.txt --clean `
            --add-data "assets/Lumos_Logo_32x32.png;assets" `
            --add-data "assets/Lumos_Laser_Logo_1024x236.png;assets" `
            --add-data "assets/Osc_Diagram.png;assets" `
            --add-data "assets/Screenshot.png;assets"
        shell: pwsh

      - name: Build with PyInstaller (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller main.py \
            --onefile \
            --windowed \
            --name Reprate_Calculator \
            --icon=Lumos_Logo_32x32.icns \
            --clean \
            --add-data "assets/Lumos_Logo_32x32.png:assets" \
            --add-data "assets/Lumos_Laser_Logo_1024x236.png:assets" \
            --add-data "assets/Osc_Diagram.png:assets" \
            --add-data "assets/Screenshot.png:assets"
        shell: bash

      # ----------------------------
      # 6. Upload artifacts
      # ----------------------------
      - name: Upload built app/executable
        uses: actions/upload-artifact@v4
        with:
          name: Reprate_Calculator-${{ matrix.os }}
          path: |
            dist/*

# # ----------------------------
# # 7. Create GitHub release (if not exists) and upload assets
# # ----------------------------
# - name: Create Release
#   id: create_release
#   uses: actions/create-release@v2
#   with:
#     tag_name: v1.0.0      # Or use ${{ github.sha }} for unique tag per commit
#     release_name: Reprate_Calculator v1.0.0
#     draft: false
#     prerelease: false
#   env:
#     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# - name: Upload Release Asset (Windows)
#   if: matrix.os == 'windows-latest'
#   uses: actions/upload-release-asset@v1
#   with:
#     upload_url: ${{ steps.create_release.outputs.upload_url }}
#     asset_path: dist/Reprate_Calculator.exe
#     asset_name: Reprate_Calculator_Windows.exe
#     asset_content_type: application/octet-stream

# - name: Upload Release Asset (macOS)
#   if: matrix.os == 'macos-latest'
#   uses: actions/upload-release-asset@v1
#   with:
#     upload_url: ${{ steps.create_release.outputs.upload_url }}
#     asset_path: dist/Reprate_Calculator
#     asset_name: Reprate_Calculator_macOS.zip
#     asset_content_type: application/zip
