name: Build and Release Reprate_Calculator

on:
  push:
    tags:
      - 'v*.*.*'   # Trigger on version tags like v1.0.0
  workflow_dispatch: # Optional: manual trigger

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build executable with PyInstaller
  run: |
    if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
      DATA_FILES="Lumos_Logo_32x32.png;Lumos_Logo_32x32.ico;Lumos_Laser_Logo_1024x236.png;Osc_Diagram.png;Screenshot.png"
      pyinstaller --noconfirm --onefile --add-data "$DATA_FILES" main.py
    else
      # macOS: add each file separately
      pyinstaller --noconfirm --onefile --windowed \
        --add-data "Lumos_Logo_32x32.png:." \
        --add-data "Lumos_Logo_32x32.ico:." \
        --add-data "Lumos_Laser_Logo_1024x236.png:." \
        --add-data "Osc_Diagram.png:." \
        --add-data "Screenshot.png:." \
        main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Reprate_Calculator-${{ matrix.os }}
          path: dist/main*

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: Reprate_Calculator-windows-latest
          path: ./builds/windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: Reprate_Calculator-macos-latest
          path: ./builds/macos

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./builds/windows/main.exe
            ./builds/macos/main
