name: Build Executables

on:
  push:
    tags:
      - "v*"   # only build when you push a version tag like v1.0
  workflow_dispatch:  # allows manual trigger

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS App
        run: |
          pyinstaller --onefile --windowed --icon=images/Lumos_Logo_32x32.icns main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: dist/
