name: Build and Release Reprate_Calculator

permissions:
  contents: write   # Needed to create GitHub releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller main.py --onefile --windowed --name Reprate_Calculator --icon Lumos_Logo_32x32.ico --clean `
            --add-data "Lumos_Logo_32x32.png;." `
            --add-data "Lumos_Logo_32x32.ico;." `
            --add-data "Lumos_Laser_Logo_1024x236.png;." `
            --add-data "Osc_Diagram.png;." `
            --add-data "Screenshot.png;."
        shell: cmd

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller main.py \
            --onefile \
            --windowed \
            --name Reprate_Calculator \
            --icon Lumos_Logo_32x32.icns \
            --clean \
            --add-data "Lumos_Logo_32x32.png:." \
            --add-data "Lumos_Logo_32x32.ico:." \
            --add-data "Lumos_Laser_Logo_1024x236.png:." \
            --add-data "Osc_Diagram.png:." \
            --add-data "Screenshot.png:."
        shell: bash

      - name: Zip macOS app
        if: runner.os == 'macOS'
        run: |
          cd dist
          zip -r Reprate_Calculator_macOS.zip Reprate_Calculator.app
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          files: |
            dist/Reprate_Calculator.exe
            dist/Reprate_Calculator_macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
