name: Build Reprate_Calculator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.11]

    steps:
      # ----------------------------
      # 1. Checkout repository
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------
      # 2. Set up Python
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------
      # 3. Install dependencies
      # ----------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      # ----------------------------
      # 4. Prepare assets folder
      # ----------------------------
      - name: Prepare assets (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path assets
        Copy-Item Lumos_Logo_32x32.png,Lumos_Logo_32x32.ico,Lumos_Laser_Logo_1024x236.png,Osc_Diagram.png,Screenshot.png assets

      - name: Prepare assets (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p assets
          cp Lumos_Logo_32x32.png Lumos_Logo_32x32.ico Lumos_Laser_Logo_1024x236.png Osc_Diagram.png Screenshot.png assets/

      # ----------------------------
      # 5. Build Windows executable
      # ----------------------------
      - name: Build Windows executable
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          pyinstaller main.py --onefile --windowed --name Reprate_Calculator --icon=assets\Lumos_Logo_32x32.ico --add-data "assets\Lumos_Logo_32x32.png;assets" --add-data "assets\Lumos_Laser_Logo_1024x236.png;assets" --add-data "assets\Osc_Diagram.png;assets" --add-data "assets\Screenshot.png;assets"

      # ----------------------------
      # 6. Build macOS .app
      # ----------------------------
      - name: Build macOS App
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          pyinstaller main.py --windowed --name Reprate_Calculator --icon=assets/Lumos_Logo_32x32.icns --add-data "assets/Lumos_Logo_32x32.png:assets" --add-data "assets/Lumos_Laser_Logo_1024x236.png:assets" --add-data "assets/Osc_Diagram.png:assets" --add-data "assets/Screenshot.png:assets" --distpath dist

          # Create a .dmg for macOS distribution
          brew install create-dmg || true
          create-dmg dist/Reprate_Calculator.app dist/Reprate_Calculator.dmg --overwrite --dmg-title="Reprate_Calculator"

      # ----------------------------
      # 7. Upload artifacts
      # ----------------------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Reprate_Calculator-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/Reprate_Calculator.app
