name: Build and Release Reprate_Calculator

# Explicitly grant permissions for release creation
permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.11]

    steps:
      # ----------------------------
      # 1. Checkout repository
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------
      # 2. Set up Python
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------
      # 3. Install dependencies
      # ----------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      # ----------------------------
      # 4. Prepare assets
      # ----------------------------
      - name: Prepare assets (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Force -Path assets
          Copy-Item Lumos_Logo_32x32.png,Lumos_Logo_32x32.ico,Lumos_Laser_Logo_1024x236.png,Osc_Diagram.png,Screenshot.png -Destination assets
        shell: pwsh

      - name: Prepare assets (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p assets
          cp Lumos_Logo_32x32.png Lumos_Logo_32x32.ico Lumos_Laser_Logo_1024x236.png Osc_Diagram.png Screenshot.png assets/
        shell: bash

      # ----------------------------
      # 5. Build executable/app
      # ----------------------------
      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller main.py `
            --onefile `
            --windowed `
            --name Reprate_Calculator `
            --icon=Lumos_Logo_32x32.ico `
            --clean `
            --add-data "assets/Lumos_Logo_32x32.png;assets" `
            --add-data "assets/Lumos_Laser_Logo_1024x236.png;assets" `
            --add-data "assets/Osc_Diagram.png;assets" `
            --add-data "assets/Screenshot.png;assets"
        shell: pwsh

      - name: Build with PyInstaller (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller main.py \
            --onefile \
            --windowed \
            --name Reprate_Calculator \
            --icon=Lumos_Logo_32x32.icns \
            --clean \
            --add-data "assets/Lumos_Logo_32x32.png:assets" \
            --add-data "assets/Lumos_Laser_Logo_1024x236.png:assets" \
            --add-data "assets/Osc_Diagram.png:assets" \
            --add-data "assets/Screenshot.png:assets"
        shell: bash

      # ----------------------------
      # 6. Create GitHub release
      # ----------------------------
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ----------------------------
      # 7. Upload release assets
      # ----------------------------
      - name: Upload Windows Release Asset
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Reprate_Calculator.exe

      - name: Upload macOS Release Asset
        if: runner.os == 'macOS'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Reprate_Calculator
