name: Build and Release Reprate_Calculator

# Allow workflow to create releases
permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.11]

    steps:
      # ----------------------------
      # 1. Checkout repository
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------
      # 2. Set up Python
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------
      # 3. Install dependencies
      # ----------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      # ----------------------------
      # 4. Build executable/app
      # ----------------------------
      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller main.py --onefile --windowed --name Reprate_Calculator --icon=Lumos_Logo_32x32.ico --clean `
            --add-data "Lumos_Logo_32x32.png;assets" `
            --add-data "Lumos_Laser_Logo_1024x236.png;assets" `
            --add-data "Osc_Diagram.png;assets" `
            --add-data "Screenshot.png;assets"
        shell: pwsh

      - name: Build with PyInstaller (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller main.py \
            --onefile \
            --windowed \
            --name Reprate_Calculator \
            --icon Lumos_Logo_32x32.icns \
            --clean \
            --add-data "Lumos_Logo_32x32.png:assets" \
            --add-data "Lumos_Laser_Logo_1024x236.png:assets" \
            --add-data "Osc_Diagram.png:assets" \
            --add-data "Screenshot.png:assets"
        shell: bash

      # ----------------------------
      # 5. Zip macOS app for release
      # ----------------------------
      - name: Zip macOS executable
        if: runner.os == 'macOS'
        run: |
          cd dist
          zip -r Reprate_Calculator_macOS.zip Reprate_Calculator
        shell: bash

      # ----------------------------
      # 6. Upload Release to GitHub
      # ----------------------------
      - name: Publish release with assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          files: |
            dist/Reprate_Calculator.exe
            dist/Reprate_Calculator_macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
