name: Release Web App

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive Web App
        run: |
          zip -r Reprate_Calculator_WebApp.zip index.html styles.css script.js Lumos_Logo_32x32.png Lumos_Logo_32x32.ico Lumos_Laser_Logo_1024x236.png Osc_Diagram.png

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Reprate_Calculator_WebApp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
