name: Build Reprate Calculator

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0
  workflow_dispatch:  # Allow manual run

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=Lumos_Logo_32x32.ico main.py

      - name: Create release artifact
        uses: actions/upload-artifact@v4
        with:
          name: Reprate_Calculator_Windows
          path: dist/main.exe

      - name: Publish Windows release
        uses: ncipollo/release-action@v2
        with:
          artifacts: dist/main.exe
          tag: ${{ github.ref_name }}
          name: Reprate Calculator Windows

  build-macos:
    name: Build macOS Executable
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build macOS app with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=Lumos_Logo_32x32.icns main.py

      - name: Create release artifact
        uses: actions/upload-artifact@v4
        with:
          name: Reprate_Calculator_macOS
          path: dist/main

      - name: Publish macOS release
        uses: ncipollo/release-action@v2
        with:
          artifacts: dist/main
          tag: ${{ github.ref_name }}
          name: Reprate Calculator macOS
