name: Build and Release

on:
  push:
    tags:
      - "v1.0"   # e.g. v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Windows build
      - name: Build Windows executable
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --windowed --icon=Lumos_Logo_32x32.ico main.py

      # macOS build
      - name: Build macOS app
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --onefile --windowed --icon=Lumos_Logo_32x32.icns main.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Reprate-Calculator-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
